### ISSUE TITLE
QUESTION about prompts

### ISSUE THREAD

**Issue by gray311** [eujhwang/meme-cap#1]
Hello, after reading your paper, I found this to be a very interesting work. However, I have a question. What prompts did you use when conducting the experiments? Was it just "What is the meme poster trying to convey?" or did you have a series of similar prompts?

**Comment by eujhwang** [comment]
Hello,

We did not use a series of similar prompts.

The prompt used for our experiments are:

> <image>This is a meme with the title “{title}”. The image description is “{image caption}”. The following text is written inside the meme: “{OCR text}”. What is the meme poster trying to convey?
> Answer:
